
debug = true
logLevel = "INFO"
defaultEntryPoints = [ "http" ]

[entryPoints]
[entryPoints.traefik]
address = ":%TraefikApiPort%"
[entryPoints.http]
address = ":%TraefikPort%"

[api]
entryPoint = "traefik"
dashboard = true
debug = true

[servicefabric]
clustermanagementurl = "%ClusterManagementUrl%"
apiversion = "3.0"

