
debug = true
logLevel = "INFO"
checkNewVersion = false
defaultEntryPoints = [ "http" ]

[serverTransport]
maxIdleConnsPerHost = "%MaxIdleConnsPerHost%"
[serverTransport.forwardingTimeouts]
dialTimeout = "%DialTimeout%"
responseHeaderTimeout = "%ResponseHeaderTimeout%"
idleConnTimeout = "%IdleConnTimeout%"

[entryPoints]
[entryPoints.traefik]
address = ":%TraefikApiPort%"
[entryPoints.http]
address = ":%TraefikPort%"
[entryPoints.http.transport]
[entryPoints.http.transport.lifeCycle]
requestAcceptGraceTimeout = "%RequestAcceptGraceTimeout%"
graceTimeOut = "%GraceTimeout%"
[entryPoints.http.transport.respondingTimeouts]
readTimeout = "%ReadTimeout%"
writeTimeout = "%WriteTimeout%"
idleTimeout = "%IdleTimeout%"

[api]
insecure = true
dashboard = true
debug = true

[ping]
entryPoint = "http"

[providers]
[providers.file]
directory = "%TraefikConfDir%"
watch = true

[retry]
