
debug = true
logLevel = "INFO"
checkNewVersion = false
defaultEntryPoints = [ "http" ]

[entryPoints]
[entryPoints.traefik]
address = ":%TraefikApiPort%"
[entryPoints.http]
address = ":%TraefikPort%"

[api]
entryPoint = "traefik"
dashboard = true
debug = true

[ping]
entryPoint = "http"

[servicefabric]
clustermanagementurl = "http://localhost:%ClusterManagementPort%"
apiversion = "3.0"

[retry]

[lifeCycle]
graceTimeOut = "%GraceTimeout%"
requestAcceptGraceTimeout = "%RequestAcceptGraceTimeout%"

[respondingTimeouts]
readTimeout = "%ReadTimeout%"
writeTimeout = "%WriteTimeout%"
idleTimeout = "%IdleTimeout%"

[forwardingTimeouts]
dialTimeout = "%DialTimeout%"
responseHeaderTimeout = "%ResponseHeaderTimeout%"
